### ISSUE TITLE
Can I use this code for human silhouette extraction?

### ISSUE THREAD

**Issue by prb2307** [rafaelpadilla/Detecting-lost-objects-with-Deep-Learning#1]
@rafaelpadilla  I was wondering whether I can use this code for human silhouette extraction.
I would like to extract the human silhouettes from the video. I would appreciate your advice. Thanks.

**Comment by rafaelpadilla** [comment]
Dear @prashant-bansod ,

The code presented in this repo does not apply for human silhouette extraction. This project is related to the [VDAO](http://www02.smt.ufrj.br/~tvdigital/database/objects/), a database suited for abandoned objects.

I believe your topic is somehow related to Semantic Segmentation, which is not my expertise for the moment. I am sure there are plenty of papers and open repositories under this topic.

Best regards,
Rafael
